### ISSUE TITLE
Errors in SSL negotiation / SSL 협상 중 오류 해결

### ISSUE THREAD

**Issue by gnh1201** [gnh1201/caterpillar#32]
## 요약
Windows 환경에서 테스트 하던 중 SSL 협상 과정에서 몇가지 오류가 발견되어 기록함.

### 시스템에 openssl이 설치되어 있지 않은 경우 처리 (Windows)
시스템에 openssl이 설치되어 있지 않은 경우 `FileNotFoundError` 예외가 일어나지만, 현재 예외를 명시적으로 처리하지 않고 있다. 이 부분 openssl 설치를 권장하던지, 인증서를 동적으로 생성하지 않고 기본 인증서를 사용하던지 등 예외 처리가 필요함.

```
[2024-07-11 17:08:57,976] ERROR server: [*] Skipped generating the certificate.
Traceback (most recent call last):
  File "C:\Users\knh94\caterpillar-logging-system\server.py", line 183, in proxy_connect
    p1 = Popen([openssl_binpath, "req", "-new", "-key", certkey, "-subj", "/CN=%s" % hostname], stdout=PIPE)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
Traceback (most recent call last):
  File "C:\Users\knh94\caterpillar-logging-system\server.py", line 223, in proxy_server
    conn, data = proxy_connect(webserver, conn)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\knh94\caterpillar-logging-system\server.py", line 194, in proxy_connect
    context.load_cert_chain(certpath, certkey)
FileNotFoundError: [Errno 2] No such file or directory
```

### CA 인증서 미설치에 따른 오류
Windows 환경에 대한 문서 추가하길 바람. README.md에 언급된 것은 Linux에 해당함.

```
Traceback (most recent call last):
  File "C:\Users\knh94\caterpillar-logging-system\server.py", line 223, in proxy_server
    conn, data = proxy_connect(webserver, conn)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\knh94\caterpillar-logging-system\server.py", line 197, in proxy_connect
    conn = context.wrap_socket(conn, server_side=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\ssl.py", line 1042, in _create
    self.do_handshake()
  File "C:\Python312\Lib\ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\knh94\caterpillar-logging-system\server.py", line 228, in proxy_server
    raise Exception(
Exception: SSL negotiation failed. (example.org:443) [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1000)
Exception ignored in thread started by: <function conn_string at 0x000002054B1DA2A0>
Traceback (most recent call last):
  File "C:\Users\knh94\caterpillar-logging-system\server.py", line 154, in conn_string
    proxy_server(webserver, port, scheme, method, url, conn, addr, data)
  File "C:\Users\knh94\caterpillar-logging-system\server.py", line 481, in proxy_server
    conn.sendall(b"HTTP/1.1 403 Forbidden\r\n\r\n{\"status\":403}")
OSError: [WinError 10038] (***broken message***)
```

**Comment by gnh1201** [comment]
해결됨. https://github.com/gnh1201/caterpillar/pull/34
